### ISSUE TITLE
Not sure if I'm installing it right!

### ISSUE THREAD

**Issue by mara90** [jehna/ga-lite#15]
Hi Jesse, I know that its not an issue, but I'm not sure what I'm doing wrong!?
I have wordpress site and I'm required to make the Google pagespeed 100/100, so I've searched everywhere and came across your plugin.
As you mentioned I copied the code you posted to the body of my site and I added the google analytics tracking code which is UA-XXXXXXXX-X. The score is still the same, can you please tell me if theres something I'm missing or should do ?

Thanks a lot

**Comment by jehna** [comment]
Just tested to check that the `ga-lite` gives 100/100 with a simple test site, so I think you're doing something wrong.

Did you remove the original Google Analytics code?

Maybe I can give a look if you have the site somewhere public?

**Comment by mara90** [comment]
So first, I didnt  remove google analytics code ( my mistake) and now I did and its still showing the same error.
the site is www.hesslerlaw.com 
The thing is I'm also using Tag Manager, and its also showing an error, so I really hope your plugin can help me with those errors. I really appreciate your fast respond!

**Comment by jehna** [comment]
With a quick look it seems that the tag manager is loading the `ga.js`. The tag manager script itself is also lowering your page speed score.

So you'll need to log in to the tag manager and remove the google analytics from there (or remove the tag manager script altogether from the site).

Closing this issue, since the `ga-lite.js` is not lowering the score.

**Comment by mara90** [comment]
Oh thank you!! I've been wondering where this "ga.js" is coming from, and I'll remove Google Analytics from the Tag Manager and test the site again.
Thanks again :)
