### ISSUE TITLE
No HTTP response detected

### ISSUE THREAD

**Issue by aravon72** [jehna/ga-lite#56]
Hi there (I hope this is the right place to raise issues),

I was using v1 of ga-lite and was extremely pleased.
I admit I don't check my analytics too often, and yesterday I've found out Google says my site is not using the needed code for several months now. So I came back here and found out there's a new version.

I've replaced v1 code with the v2 one, but I'm getting a red result from the Google Tag Assistant's Chrome addon, with the following errors:

1. No HTTP response detected
2. Missing analytics.js script

Now, I can realize the missing js ofcourse hence the 2nd error should be ignored, as we're using galite.js, but can the 1st error be ignored as well?

TIA,
David.

PS: This is the [site](https://www.wp-killer.co.il) I'm using ga-lite on is if you need to look at the code.

**Comment by jehna** [comment]
Hey, as a fast response: you should be okay.

You can check this issue for discussion about a similar issue as yours:

https://github.com/jehna/ga-lite/issues/54#issuecomment-358964083

In a nutshell: it should be okay, Google's tools just does not detect ga-lite because it's not officially supported

**Comment by jehna** [comment]
Closing this issue due inactivity. Please reopen if you're still experiencing issues :)
