### ISSUE TITLE
How about releasing an AMP Analytics version?

### ISSUE THREAD

**Issue by Hoodlum-Z** [jehna/ga-lite#70]
This plugin gets excellent reviews, but I've just realised that I am going to miss out because I've converted my WordPress to Native AMP on every page and no longer have regular Google analytics.

Will this be possible, at some point, please?

**Comment by jehna** [comment]
How does analytics work with AMP sites? Could you link some documentation?

Does regular analytics.js work with the AMP sites?

**Comment by jehna** [comment]
I did a quick check on the way AMP handles analytics, and here's my findings:

- You should always only use [`<amp-analytics>`](https://developers.google.com/analytics/devguides/collection/amp-analytics/) tag to fire analytics events on an AMP page
- The project [endorses](https://www.ampproject.org/docs/analytics/analytics_amp) you to [open an issue to `approject/amphtml` repo](https://github.com/ampproject/amphtml/issues/new) if an analytics vendor is not yet supported. I strongly think `ga-lite` should not be supported in itself, because it's a client for Google Analytics, which is already well supported by AMP
- AMP uses its own custom component framework, which is completely different from how a "normal" website works. I think supporting `amp-analytics-0.1.js` feature set is outside the scope of ga-lite project.

Please correct me if I got anything wrong, didn't spend that much time on this yet. Or if you have any suggestions about how ga-lite could support AMP pages

**Comment by Hoodlum-Z** [comment]
No problem, thanks for your time.
